#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path("/root/bot/raqat_bot")
DEFAULT_CSV = ROOT / "data" / "halal_ingredients_seed.csv"
DEFAULT_JSON = ROOT / "data" / "halal_ingredients_seed.json"
OUT = ROOT / "mobile_flutter" / "lib" / "content" / "halal_ingredients_db.dart"


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def _load_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    if DEFAULT_CSV.exists():
        with DEFAULT_CSV.open("r", encoding="utf-8", newline="") as f:
            for row in csv.DictReader(f):
                rows.append(
                    {
                        "risk": (row.get("risk") or "").strip().upper(),
                        "key": (row.get("key") or "").strip().lower(),
                        "label_kk": (row.get("label_kk") or "").strip(),
                    }
                )
    if not rows and DEFAULT_JSON.exists():
        data = json.loads(DEFAULT_JSON.read_text(encoding="utf-8"))
        if isinstance(data, list):
            for r in data:
                if isinstance(r, dict):
                    rows.append(
                        {
                            "risk": str(r.get("risk", "")).strip().upper(),
                            "key": str(r.get("key", "")).strip().lower(),
                            "label_kk": str(r.get("label_kk", "")).strip(),
                        }
                    )
    clean: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for r in rows:
        if r["risk"] not in {"HARAM", "MUSHKIL"}:
            continue
        if not r["key"] or not r["label_kk"]:
            continue
        sig = (r["risk"], r["key"])
        if sig in seen:
            continue
        seen.add(sig)
        clean.append(r)
    clean.sort(key=lambda x: (x["risk"], x["key"]))
    return clean


def _render(rows: list[dict[str, str]]) -> str:
    lines = [
        "class HalalIngredientFlag {",
        "  const HalalIngredientFlag({",
        "    required this.key,",
        "    required this.risk,",
        "    required this.labelKk,",
        "  });",
        "",
        "  final String key;",
        "  final String risk; // HARAM | MUSHKIL",
        "  final String labelKk;",
        "}",
        "",
        "class HalalIngredientsDb {",
        "  HalalIngredientsDb._();",
        "",
        "  // AUTO-GENERATED by scripts/generate_halal_db_dart.py",
        "  static const List<HalalIngredientFlag> flags = [",
    ]
    for r in rows:
        lines.append(
            f"    HalalIngredientFlag(key: '{_escape(r['key'])}', risk: '{r['risk']}', labelKk: '{_escape(r['label_kk'])}'),"
        )
    lines += [
        "  ];",
        "",
        "  static List<String> scan(String input) {",
        "    final hay = input.toLowerCase();",
        "    final out = <String>[];",
        "    for (final f in flags) {",
        "      if (hay.contains(f.key)) {",
        "        out.add('[${f.risk}] ${f.labelKk}');",
        "      }",
        "    }",
        "    return out.toSet().toList()..sort();",
        "  }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    rows = _load_rows()
    if not rows:
        raise SystemExit("No rows loaded from CSV/JSON seed.")
    OUT.write_text(_render(rows), encoding="utf-8")
    print(f"generated: {OUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
