/** Auto-generated by scripts/generate-qcf4-bundled-page-map.cjs — do not edit. */
import type { Qcf4PageJson } from "./qcf4Types";

export function loadQcf4BundledPageJson(page: number): Qcf4PageJson | null {
  switch (page) {
    case 1:
      return require("../../assets/quran/qcf4/pages/001.json") as Qcf4PageJson;
    case 2:
      return require("../../assets/quran/qcf4/pages/002.json") as Qcf4PageJson;
    case 3:
      return require("../../assets/quran/qcf4/pages/003.json") as Qcf4PageJson;
    case 4:
      return require("../../assets/quran/qcf4/pages/004.json") as Qcf4PageJson;
    case 5:
      return require("../../assets/quran/qcf4/pages/005.json") as Qcf4PageJson;
    case 6:
      return require("../../assets/quran/qcf4/pages/006.json") as Qcf4PageJson;
    case 7:
      return require("../../assets/quran/qcf4/pages/007.json") as Qcf4PageJson;
    case 8:
      return require("../../assets/quran/qcf4/pages/008.json") as Qcf4PageJson;
    case 9:
      return require("../../assets/quran/qcf4/pages/009.json") as Qcf4PageJson;
    case 10:
      return require("../../assets/quran/qcf4/pages/010.json") as Qcf4PageJson;
    case 11:
      return require("../../assets/quran/qcf4/pages/011.json") as Qcf4PageJson;
    case 12:
      return require("../../assets/quran/qcf4/pages/012.json") as Qcf4PageJson;
    case 13:
      return require("../../assets/quran/qcf4/pages/013.json") as Qcf4PageJson;
    case 14:
      return require("../../assets/quran/qcf4/pages/014.json") as Qcf4PageJson;
    case 15:
      return require("../../assets/quran/qcf4/pages/015.json") as Qcf4PageJson;
    case 16:
      return require("../../assets/quran/qcf4/pages/016.json") as Qcf4PageJson;
    case 17:
      return require("../../assets/quran/qcf4/pages/017.json") as Qcf4PageJson;
    case 18:
      return require("../../assets/quran/qcf4/pages/018.json") as Qcf4PageJson;
    case 19:
      return require("../../assets/quran/qcf4/pages/019.json") as Qcf4PageJson;
    case 20:
      return require("../../assets/quran/qcf4/pages/020.json") as Qcf4PageJson;
    case 21:
      return require("../../assets/quran/qcf4/pages/021.json") as Qcf4PageJson;
    case 22:
      return require("../../assets/quran/qcf4/pages/022.json") as Qcf4PageJson;
    case 23:
      return require("../../assets/quran/qcf4/pages/023.json") as Qcf4PageJson;
    case 24:
      return require("../../assets/quran/qcf4/pages/024.json") as Qcf4PageJson;
    case 25:
      return require("../../assets/quran/qcf4/pages/025.json") as Qcf4PageJson;
    case 26:
      return require("../../assets/quran/qcf4/pages/026.json") as Qcf4PageJson;
    case 27:
      return require("../../assets/quran/qcf4/pages/027.json") as Qcf4PageJson;
    case 28:
      return require("../../assets/quran/qcf4/pages/028.json") as Qcf4PageJson;
    case 29:
      return require("../../assets/quran/qcf4/pages/029.json") as Qcf4PageJson;
    case 30:
      return require("../../assets/quran/qcf4/pages/030.json") as Qcf4PageJson;
    case 31:
      return require("../../assets/quran/qcf4/pages/031.json") as Qcf4PageJson;
    case 32:
      return require("../../assets/quran/qcf4/pages/032.json") as Qcf4PageJson;
    case 33:
      return require("../../assets/quran/qcf4/pages/033.json") as Qcf4PageJson;
    case 34:
      return require("../../assets/quran/qcf4/pages/034.json") as Qcf4PageJson;
    case 35:
      return require("../../assets/quran/qcf4/pages/035.json") as Qcf4PageJson;
    case 36:
      return require("../../assets/quran/qcf4/pages/036.json") as Qcf4PageJson;
    case 37:
      return require("../../assets/quran/qcf4/pages/037.json") as Qcf4PageJson;
    case 38:
      return require("../../assets/quran/qcf4/pages/038.json") as Qcf4PageJson;
    case 39:
      return require("../../assets/quran/qcf4/pages/039.json") as Qcf4PageJson;
    case 40:
      return require("../../assets/quran/qcf4/pages/040.json") as Qcf4PageJson;
    case 41:
      return require("../../assets/quran/qcf4/pages/041.json") as Qcf4PageJson;
    case 42:
      return require("../../assets/quran/qcf4/pages/042.json") as Qcf4PageJson;
    case 43:
      return require("../../assets/quran/qcf4/pages/043.json") as Qcf4PageJson;
    case 44:
      return require("../../assets/quran/qcf4/pages/044.json") as Qcf4PageJson;
    case 45:
      return require("../../assets/quran/qcf4/pages/045.json") as Qcf4PageJson;
    case 46:
      return require("../../assets/quran/qcf4/pages/046.json") as Qcf4PageJson;
    case 47:
      return require("../../assets/quran/qcf4/pages/047.json") as Qcf4PageJson;
    case 48:
      return require("../../assets/quran/qcf4/pages/048.json") as Qcf4PageJson;
    case 49:
      return require("../../assets/quran/qcf4/pages/049.json") as Qcf4PageJson;
    case 50:
      return require("../../assets/quran/qcf4/pages/050.json") as Qcf4PageJson;
    case 51:
      return require("../../assets/quran/qcf4/pages/051.json") as Qcf4PageJson;
    case 52:
      return require("../../assets/quran/qcf4/pages/052.json") as Qcf4PageJson;
    case 53:
      return require("../../assets/quran/qcf4/pages/053.json") as Qcf4PageJson;
    case 54:
      return require("../../assets/quran/qcf4/pages/054.json") as Qcf4PageJson;
    case 55:
      return require("../../assets/quran/qcf4/pages/055.json") as Qcf4PageJson;
    case 56:
      return require("../../assets/quran/qcf4/pages/056.json") as Qcf4PageJson;
    case 57:
      return require("../../assets/quran/qcf4/pages/057.json") as Qcf4PageJson;
    case 58:
      return require("../../assets/quran/qcf4/pages/058.json") as Qcf4PageJson;
    case 59:
      return require("../../assets/quran/qcf4/pages/059.json") as Qcf4PageJson;
    case 60:
      return require("../../assets/quran/qcf4/pages/060.json") as Qcf4PageJson;
    case 61:
      return require("../../assets/quran/qcf4/pages/061.json") as Qcf4PageJson;
    case 62:
      return require("../../assets/quran/qcf4/pages/062.json") as Qcf4PageJson;
    case 63:
      return require("../../assets/quran/qcf4/pages/063.json") as Qcf4PageJson;
    case 64:
      return require("../../assets/quran/qcf4/pages/064.json") as Qcf4PageJson;
    case 65:
      return require("../../assets/quran/qcf4/pages/065.json") as Qcf4PageJson;
    case 66:
      return require("../../assets/quran/qcf4/pages/066.json") as Qcf4PageJson;
    case 67:
      return require("../../assets/quran/qcf4/pages/067.json") as Qcf4PageJson;
    case 68:
      return require("../../assets/quran/qcf4/pages/068.json") as Qcf4PageJson;
    case 69:
      return require("../../assets/quran/qcf4/pages/069.json") as Qcf4PageJson;
    case 70:
      return require("../../assets/quran/qcf4/pages/070.json") as Qcf4PageJson;
    case 71:
      return require("../../assets/quran/qcf4/pages/071.json") as Qcf4PageJson;
    case 72:
      return require("../../assets/quran/qcf4/pages/072.json") as Qcf4PageJson;
    case 73:
      return require("../../assets/quran/qcf4/pages/073.json") as Qcf4PageJson;
    case 74:
      return require("../../assets/quran/qcf4/pages/074.json") as Qcf4PageJson;
    case 75:
      return require("../../assets/quran/qcf4/pages/075.json") as Qcf4PageJson;
    case 76:
      return require("../../assets/quran/qcf4/pages/076.json") as Qcf4PageJson;
    case 77:
      return require("../../assets/quran/qcf4/pages/077.json") as Qcf4PageJson;
    case 78:
      return require("../../assets/quran/qcf4/pages/078.json") as Qcf4PageJson;
    case 79:
      return require("../../assets/quran/qcf4/pages/079.json") as Qcf4PageJson;
    case 80:
      return require("../../assets/quran/qcf4/pages/080.json") as Qcf4PageJson;
    case 81:
      return require("../../assets/quran/qcf4/pages/081.json") as Qcf4PageJson;
    case 82:
      return require("../../assets/quran/qcf4/pages/082.json") as Qcf4PageJson;
    case 83:
      return require("../../assets/quran/qcf4/pages/083.json") as Qcf4PageJson;
    case 84:
      return require("../../assets/quran/qcf4/pages/084.json") as Qcf4PageJson;
    case 85:
      return require("../../assets/quran/qcf4/pages/085.json") as Qcf4PageJson;
    case 86:
      return require("../../assets/quran/qcf4/pages/086.json") as Qcf4PageJson;
    case 87:
      return require("../../assets/quran/qcf4/pages/087.json") as Qcf4PageJson;
    case 88:
      return require("../../assets/quran/qcf4/pages/088.json") as Qcf4PageJson;
    case 89:
      return require("../../assets/quran/qcf4/pages/089.json") as Qcf4PageJson;
    case 90:
      return require("../../assets/quran/qcf4/pages/090.json") as Qcf4PageJson;
    case 91:
      return require("../../assets/quran/qcf4/pages/091.json") as Qcf4PageJson;
    case 92:
      return require("../../assets/quran/qcf4/pages/092.json") as Qcf4PageJson;
    case 93:
      return require("../../assets/quran/qcf4/pages/093.json") as Qcf4PageJson;
    case 94:
      return require("../../assets/quran/qcf4/pages/094.json") as Qcf4PageJson;
    case 95:
      return require("../../assets/quran/qcf4/pages/095.json") as Qcf4PageJson;
    case 96:
      return require("../../assets/quran/qcf4/pages/096.json") as Qcf4PageJson;
    case 97:
      return require("../../assets/quran/qcf4/pages/097.json") as Qcf4PageJson;
    case 98:
      return require("../../assets/quran/qcf4/pages/098.json") as Qcf4PageJson;
    case 99:
      return require("../../assets/quran/qcf4/pages/099.json") as Qcf4PageJson;
    case 100:
      return require("../../assets/quran/qcf4/pages/100.json") as Qcf4PageJson;
    case 101:
      return require("../../assets/quran/qcf4/pages/101.json") as Qcf4PageJson;
    case 102:
      return require("../../assets/quran/qcf4/pages/102.json") as Qcf4PageJson;
    case 103:
      return require("../../assets/quran/qcf4/pages/103.json") as Qcf4PageJson;
    case 104:
      return require("../../assets/quran/qcf4/pages/104.json") as Qcf4PageJson;
    case 105:
      return require("../../assets/quran/qcf4/pages/105.json") as Qcf4PageJson;
    case 106:
      return require("../../assets/quran/qcf4/pages/106.json") as Qcf4PageJson;
    case 107:
      return require("../../assets/quran/qcf4/pages/107.json") as Qcf4PageJson;
    case 108:
      return require("../../assets/quran/qcf4/pages/108.json") as Qcf4PageJson;
    case 109:
      return require("../../assets/quran/qcf4/pages/109.json") as Qcf4PageJson;
    case 110:
      return require("../../assets/quran/qcf4/pages/110.json") as Qcf4PageJson;
    case 111:
      return require("../../assets/quran/qcf4/pages/111.json") as Qcf4PageJson;
    case 112:
      return require("../../assets/quran/qcf4/pages/112.json") as Qcf4PageJson;
    case 113:
      return require("../../assets/quran/qcf4/pages/113.json") as Qcf4PageJson;
    case 114:
      return require("../../assets/quran/qcf4/pages/114.json") as Qcf4PageJson;
    case 115:
      return require("../../assets/quran/qcf4/pages/115.json") as Qcf4PageJson;
    case 116:
      return require("../../assets/quran/qcf4/pages/116.json") as Qcf4PageJson;
    case 117:
      return require("../../assets/quran/qcf4/pages/117.json") as Qcf4PageJson;
    case 118:
      return require("../../assets/quran/qcf4/pages/118.json") as Qcf4PageJson;
    case 119:
      return require("../../assets/quran/qcf4/pages/119.json") as Qcf4PageJson;
    case 120:
      return require("../../assets/quran/qcf4/pages/120.json") as Qcf4PageJson;
    case 121:
      return require("../../assets/quran/qcf4/pages/121.json") as Qcf4PageJson;
    case 122:
      return require("../../assets/quran/qcf4/pages/122.json") as Qcf4PageJson;
    case 123:
      return require("../../assets/quran/qcf4/pages/123.json") as Qcf4PageJson;
    case 124:
      return require("../../assets/quran/qcf4/pages/124.json") as Qcf4PageJson;
    case 125:
      return require("../../assets/quran/qcf4/pages/125.json") as Qcf4PageJson;
    case 126:
      return require("../../assets/quran/qcf4/pages/126.json") as Qcf4PageJson;
    case 127:
      return require("../../assets/quran/qcf4/pages/127.json") as Qcf4PageJson;
    case 128:
      return require("../../assets/quran/qcf4/pages/128.json") as Qcf4PageJson;
    case 129:
      return require("../../assets/quran/qcf4/pages/129.json") as Qcf4PageJson;
    case 130:
      return require("../../assets/quran/qcf4/pages/130.json") as Qcf4PageJson;
    case 131:
      return require("../../assets/quran/qcf4/pages/131.json") as Qcf4PageJson;
    case 132:
      return require("../../assets/quran/qcf4/pages/132.json") as Qcf4PageJson;
    case 133:
      return require("../../assets/quran/qcf4/pages/133.json") as Qcf4PageJson;
    case 134:
      return require("../../assets/quran/qcf4/pages/134.json") as Qcf4PageJson;
    case 135:
      return require("../../assets/quran/qcf4/pages/135.json") as Qcf4PageJson;
    case 136:
      return require("../../assets/quran/qcf4/pages/136.json") as Qcf4PageJson;
    case 137:
      return require("../../assets/quran/qcf4/pages/137.json") as Qcf4PageJson;
    case 138:
      return require("../../assets/quran/qcf4/pages/138.json") as Qcf4PageJson;
    case 139:
      return require("../../assets/quran/qcf4/pages/139.json") as Qcf4PageJson;
    case 140:
      return require("../../assets/quran/qcf4/pages/140.json") as Qcf4PageJson;
    case 141:
      return require("../../assets/quran/qcf4/pages/141.json") as Qcf4PageJson;
    case 142:
      return require("../../assets/quran/qcf4/pages/142.json") as Qcf4PageJson;
    case 143:
      return require("../../assets/quran/qcf4/pages/143.json") as Qcf4PageJson;
    case 144:
      return require("../../assets/quran/qcf4/pages/144.json") as Qcf4PageJson;
    case 145:
      return require("../../assets/quran/qcf4/pages/145.json") as Qcf4PageJson;
    case 146:
      return require("../../assets/quran/qcf4/pages/146.json") as Qcf4PageJson;
    case 147:
      return require("../../assets/quran/qcf4/pages/147.json") as Qcf4PageJson;
    case 148:
      return require("../../assets/quran/qcf4/pages/148.json") as Qcf4PageJson;
    case 149:
      return require("../../assets/quran/qcf4/pages/149.json") as Qcf4PageJson;
    case 150:
      return require("../../assets/quran/qcf4/pages/150.json") as Qcf4PageJson;
    case 151:
      return require("../../assets/quran/qcf4/pages/151.json") as Qcf4PageJson;
    case 152:
      return require("../../assets/quran/qcf4/pages/152.json") as Qcf4PageJson;
    case 153:
      return require("../../assets/quran/qcf4/pages/153.json") as Qcf4PageJson;
    case 154:
      return require("../../assets/quran/qcf4/pages/154.json") as Qcf4PageJson;
    case 155:
      return require("../../assets/quran/qcf4/pages/155.json") as Qcf4PageJson;
    case 156:
      return require("../../assets/quran/qcf4/pages/156.json") as Qcf4PageJson;
    case 157:
      return require("../../assets/quran/qcf4/pages/157.json") as Qcf4PageJson;
    case 158:
      return require("../../assets/quran/qcf4/pages/158.json") as Qcf4PageJson;
    case 159:
      return require("../../assets/quran/qcf4/pages/159.json") as Qcf4PageJson;
    case 160:
      return require("../../assets/quran/qcf4/pages/160.json") as Qcf4PageJson;
    case 161:
      return require("../../assets/quran/qcf4/pages/161.json") as Qcf4PageJson;
    case 162:
      return require("../../assets/quran/qcf4/pages/162.json") as Qcf4PageJson;
    case 163:
      return require("../../assets/quran/qcf4/pages/163.json") as Qcf4PageJson;
    case 164:
      return require("../../assets/quran/qcf4/pages/164.json") as Qcf4PageJson;
    case 165:
      return require("../../assets/quran/qcf4/pages/165.json") as Qcf4PageJson;
    case 166:
      return require("../../assets/quran/qcf4/pages/166.json") as Qcf4PageJson;
    case 167:
      return require("../../assets/quran/qcf4/pages/167.json") as Qcf4PageJson;
    case 168:
      return require("../../assets/quran/qcf4/pages/168.json") as Qcf4PageJson;
    case 169:
      return require("../../assets/quran/qcf4/pages/169.json") as Qcf4PageJson;
    case 170:
      return require("../../assets/quran/qcf4/pages/170.json") as Qcf4PageJson;
    case 171:
      return require("../../assets/quran/qcf4/pages/171.json") as Qcf4PageJson;
    case 172:
      return require("../../assets/quran/qcf4/pages/172.json") as Qcf4PageJson;
    case 173:
      return require("../../assets/quran/qcf4/pages/173.json") as Qcf4PageJson;
    case 174:
      return require("../../assets/quran/qcf4/pages/174.json") as Qcf4PageJson;
    case 175:
      return require("../../assets/quran/qcf4/pages/175.json") as Qcf4PageJson;
    case 176:
      return require("../../assets/quran/qcf4/pages/176.json") as Qcf4PageJson;
    case 177:
      return require("../../assets/quran/qcf4/pages/177.json") as Qcf4PageJson;
    case 178:
      return require("../../assets/quran/qcf4/pages/178.json") as Qcf4PageJson;
    case 179:
      return require("../../assets/quran/qcf4/pages/179.json") as Qcf4PageJson;
    case 180:
      return require("../../assets/quran/qcf4/pages/180.json") as Qcf4PageJson;
    case 181:
      return require("../../assets/quran/qcf4/pages/181.json") as Qcf4PageJson;
    case 182:
      return require("../../assets/quran/qcf4/pages/182.json") as Qcf4PageJson;
    case 183:
      return require("../../assets/quran/qcf4/pages/183.json") as Qcf4PageJson;
    case 184:
      return require("../../assets/quran/qcf4/pages/184.json") as Qcf4PageJson;
    case 185:
      return require("../../assets/quran/qcf4/pages/185.json") as Qcf4PageJson;
    case 186:
      return require("../../assets/quran/qcf4/pages/186.json") as Qcf4PageJson;
    case 187:
      return require("../../assets/quran/qcf4/pages/187.json") as Qcf4PageJson;
    case 188:
      return require("../../assets/quran/qcf4/pages/188.json") as Qcf4PageJson;
    case 189:
      return require("../../assets/quran/qcf4/pages/189.json") as Qcf4PageJson;
    case 190:
      return require("../../assets/quran/qcf4/pages/190.json") as Qcf4PageJson;
    case 191:
      return require("../../assets/quran/qcf4/pages/191.json") as Qcf4PageJson;
    case 192:
      return require("../../assets/quran/qcf4/pages/192.json") as Qcf4PageJson;
    case 193:
      return require("../../assets/quran/qcf4/pages/193.json") as Qcf4PageJson;
    case 194:
      return require("../../assets/quran/qcf4/pages/194.json") as Qcf4PageJson;
    case 195:
      return require("../../assets/quran/qcf4/pages/195.json") as Qcf4PageJson;
    case 196:
      return require("../../assets/quran/qcf4/pages/196.json") as Qcf4PageJson;
    case 197:
      return require("../../assets/quran/qcf4/pages/197.json") as Qcf4PageJson;
    case 198:
      return require("../../assets/quran/qcf4/pages/198.json") as Qcf4PageJson;
    case 199:
      return require("../../assets/quran/qcf4/pages/199.json") as Qcf4PageJson;
    case 200:
      return require("../../assets/quran/qcf4/pages/200.json") as Qcf4PageJson;
    case 201:
      return require("../../assets/quran/qcf4/pages/201.json") as Qcf4PageJson;
    case 202:
      return require("../../assets/quran/qcf4/pages/202.json") as Qcf4PageJson;
    case 203:
      return require("../../assets/quran/qcf4/pages/203.json") as Qcf4PageJson;
    case 204:
      return require("../../assets/quran/qcf4/pages/204.json") as Qcf4PageJson;
    case 205:
      return require("../../assets/quran/qcf4/pages/205.json") as Qcf4PageJson;
    case 206:
      return require("../../assets/quran/qcf4/pages/206.json") as Qcf4PageJson;
    case 207:
      return require("../../assets/quran/qcf4/pages/207.json") as Qcf4PageJson;
    case 208:
      return require("../../assets/quran/qcf4/pages/208.json") as Qcf4PageJson;
    case 209:
      return require("../../assets/quran/qcf4/pages/209.json") as Qcf4PageJson;
    case 210:
      return require("../../assets/quran/qcf4/pages/210.json") as Qcf4PageJson;
    case 211:
      return require("../../assets/quran/qcf4/pages/211.json") as Qcf4PageJson;
    case 212:
      return require("../../assets/quran/qcf4/pages/212.json") as Qcf4PageJson;
    case 213:
      return require("../../assets/quran/qcf4/pages/213.json") as Qcf4PageJson;
    case 214:
      return require("../../assets/quran/qcf4/pages/214.json") as Qcf4PageJson;
    case 215:
      return require("../../assets/quran/qcf4/pages/215.json") as Qcf4PageJson;
    case 216:
      return require("../../assets/quran/qcf4/pages/216.json") as Qcf4PageJson;
    case 217:
      return require("../../assets/quran/qcf4/pages/217.json") as Qcf4PageJson;
    case 218:
      return require("../../assets/quran/qcf4/pages/218.json") as Qcf4PageJson;
    case 219:
      return require("../../assets/quran/qcf4/pages/219.json") as Qcf4PageJson;
    case 220:
      return require("../../assets/quran/qcf4/pages/220.json") as Qcf4PageJson;
    case 221:
      return require("../../assets/quran/qcf4/pages/221.json") as Qcf4PageJson;
    case 222:
      return require("../../assets/quran/qcf4/pages/222.json") as Qcf4PageJson;
    case 223:
      return require("../../assets/quran/qcf4/pages/223.json") as Qcf4PageJson;
    case 224:
      return require("../../assets/quran/qcf4/pages/224.json") as Qcf4PageJson;
    case 225:
      return require("../../assets/quran/qcf4/pages/225.json") as Qcf4PageJson;
    case 226:
      return require("../../assets/quran/qcf4/pages/226.json") as Qcf4PageJson;
    case 227:
      return require("../../assets/quran/qcf4/pages/227.json") as Qcf4PageJson;
    case 228:
      return require("../../assets/quran/qcf4/pages/228.json") as Qcf4PageJson;
    case 229:
      return require("../../assets/quran/qcf4/pages/229.json") as Qcf4PageJson;
    case 230:
      return require("../../assets/quran/qcf4/pages/230.json") as Qcf4PageJson;
    case 231:
      return require("../../assets/quran/qcf4/pages/231.json") as Qcf4PageJson;
    case 232:
      return require("../../assets/quran/qcf4/pages/232.json") as Qcf4PageJson;
    case 233:
      return require("../../assets/quran/qcf4/pages/233.json") as Qcf4PageJson;
    case 234:
      return require("../../assets/quran/qcf4/pages/234.json") as Qcf4PageJson;
    case 235:
      return require("../../assets/quran/qcf4/pages/235.json") as Qcf4PageJson;
    case 236:
      return require("../../assets/quran/qcf4/pages/236.json") as Qcf4PageJson;
    case 237:
      return require("../../assets/quran/qcf4/pages/237.json") as Qcf4PageJson;
    case 238:
      return require("../../assets/quran/qcf4/pages/238.json") as Qcf4PageJson;
    case 239:
      return require("../../assets/quran/qcf4/pages/239.json") as Qcf4PageJson;
    case 240:
      return require("../../assets/quran/qcf4/pages/240.json") as Qcf4PageJson;
    case 241:
      return require("../../assets/quran/qcf4/pages/241.json") as Qcf4PageJson;
    case 242:
      return require("../../assets/quran/qcf4/pages/242.json") as Qcf4PageJson;
    case 243:
      return require("../../assets/quran/qcf4/pages/243.json") as Qcf4PageJson;
    case 244:
      return require("../../assets/quran/qcf4/pages/244.json") as Qcf4PageJson;
    case 245:
      return require("../../assets/quran/qcf4/pages/245.json") as Qcf4PageJson;
    case 246:
      return require("../../assets/quran/qcf4/pages/246.json") as Qcf4PageJson;
    case 247:
      return require("../../assets/quran/qcf4/pages/247.json") as Qcf4PageJson;
    case 248:
      return require("../../assets/quran/qcf4/pages/248.json") as Qcf4PageJson;
    case 249:
      return require("../../assets/quran/qcf4/pages/249.json") as Qcf4PageJson;
    case 250:
      return require("../../assets/quran/qcf4/pages/250.json") as Qcf4PageJson;
    case 251:
      return require("../../assets/quran/qcf4/pages/251.json") as Qcf4PageJson;
    case 252:
      return require("../../assets/quran/qcf4/pages/252.json") as Qcf4PageJson;
    case 253:
      return require("../../assets/quran/qcf4/pages/253.json") as Qcf4PageJson;
    case 254:
      return require("../../assets/quran/qcf4/pages/254.json") as Qcf4PageJson;
    case 255:
      return require("../../assets/quran/qcf4/pages/255.json") as Qcf4PageJson;
    case 256:
      return require("../../assets/quran/qcf4/pages/256.json") as Qcf4PageJson;
    case 257:
      return require("../../assets/quran/qcf4/pages/257.json") as Qcf4PageJson;
    case 258:
      return require("../../assets/quran/qcf4/pages/258.json") as Qcf4PageJson;
    case 259:
      return require("../../assets/quran/qcf4/pages/259.json") as Qcf4PageJson;
    case 260:
      return require("../../assets/quran/qcf4/pages/260.json") as Qcf4PageJson;
    case 261:
      return require("../../assets/quran/qcf4/pages/261.json") as Qcf4PageJson;
    case 262:
      return require("../../assets/quran/qcf4/pages/262.json") as Qcf4PageJson;
    case 263:
      return require("../../assets/quran/qcf4/pages/263.json") as Qcf4PageJson;
    case 264:
      return require("../../assets/quran/qcf4/pages/264.json") as Qcf4PageJson;
    case 265:
      return require("../../assets/quran/qcf4/pages/265.json") as Qcf4PageJson;
    case 266:
      return require("../../assets/quran/qcf4/pages/266.json") as Qcf4PageJson;
    case 267:
      return require("../../assets/quran/qcf4/pages/267.json") as Qcf4PageJson;
    case 268:
      return require("../../assets/quran/qcf4/pages/268.json") as Qcf4PageJson;
    case 269:
      return require("../../assets/quran/qcf4/pages/269.json") as Qcf4PageJson;
    case 270:
      return require("../../assets/quran/qcf4/pages/270.json") as Qcf4PageJson;
    case 271:
      return require("../../assets/quran/qcf4/pages/271.json") as Qcf4PageJson;
    case 272:
      return require("../../assets/quran/qcf4/pages/272.json") as Qcf4PageJson;
    case 273:
      return require("../../assets/quran/qcf4/pages/273.json") as Qcf4PageJson;
    case 274:
      return require("../../assets/quran/qcf4/pages/274.json") as Qcf4PageJson;
    case 275:
      return require("../../assets/quran/qcf4/pages/275.json") as Qcf4PageJson;
    case 276:
      return require("../../assets/quran/qcf4/pages/276.json") as Qcf4PageJson;
    case 277:
      return require("../../assets/quran/qcf4/pages/277.json") as Qcf4PageJson;
    case 278:
      return require("../../assets/quran/qcf4/pages/278.json") as Qcf4PageJson;
    case 279:
      return require("../../assets/quran/qcf4/pages/279.json") as Qcf4PageJson;
    case 280:
      return require("../../assets/quran/qcf4/pages/280.json") as Qcf4PageJson;
    case 281:
      return require("../../assets/quran/qcf4/pages/281.json") as Qcf4PageJson;
    case 282:
      return require("../../assets/quran/qcf4/pages/282.json") as Qcf4PageJson;
    case 283:
      return require("../../assets/quran/qcf4/pages/283.json") as Qcf4PageJson;
    case 284:
      return require("../../assets/quran/qcf4/pages/284.json") as Qcf4PageJson;
    case 285:
      return require("../../assets/quran/qcf4/pages/285.json") as Qcf4PageJson;
    case 286:
      return require("../../assets/quran/qcf4/pages/286.json") as Qcf4PageJson;
    case 287:
      return require("../../assets/quran/qcf4/pages/287.json") as Qcf4PageJson;
    case 288:
      return require("../../assets/quran/qcf4/pages/288.json") as Qcf4PageJson;
    case 289:
      return require("../../assets/quran/qcf4/pages/289.json") as Qcf4PageJson;
    case 290:
      return require("../../assets/quran/qcf4/pages/290.json") as Qcf4PageJson;
    case 291:
      return require("../../assets/quran/qcf4/pages/291.json") as Qcf4PageJson;
    case 292:
      return require("../../assets/quran/qcf4/pages/292.json") as Qcf4PageJson;
    case 293:
      return require("../../assets/quran/qcf4/pages/293.json") as Qcf4PageJson;
    case 294:
      return require("../../assets/quran/qcf4/pages/294.json") as Qcf4PageJson;
    case 295:
      return require("../../assets/quran/qcf4/pages/295.json") as Qcf4PageJson;
    case 296:
      return require("../../assets/quran/qcf4/pages/296.json") as Qcf4PageJson;
    case 297:
      return require("../../assets/quran/qcf4/pages/297.json") as Qcf4PageJson;
    case 298:
      return require("../../assets/quran/qcf4/pages/298.json") as Qcf4PageJson;
    case 299:
      return require("../../assets/quran/qcf4/pages/299.json") as Qcf4PageJson;
    case 300:
      return require("../../assets/quran/qcf4/pages/300.json") as Qcf4PageJson;
    case 301:
      return require("../../assets/quran/qcf4/pages/301.json") as Qcf4PageJson;
    case 302:
      return require("../../assets/quran/qcf4/pages/302.json") as Qcf4PageJson;
    case 303:
      return require("../../assets/quran/qcf4/pages/303.json") as Qcf4PageJson;
    case 304:
      return require("../../assets/quran/qcf4/pages/304.json") as Qcf4PageJson;
    case 305:
      return require("../../assets/quran/qcf4/pages/305.json") as Qcf4PageJson;
    case 306:
      return require("../../assets/quran/qcf4/pages/306.json") as Qcf4PageJson;
    case 307:
      return require("../../assets/quran/qcf4/pages/307.json") as Qcf4PageJson;
    case 308:
      return require("../../assets/quran/qcf4/pages/308.json") as Qcf4PageJson;
    case 309:
      return require("../../assets/quran/qcf4/pages/309.json") as Qcf4PageJson;
    case 310:
      return require("../../assets/quran/qcf4/pages/310.json") as Qcf4PageJson;
    case 311:
      return require("../../assets/quran/qcf4/pages/311.json") as Qcf4PageJson;
    case 312:
      return require("../../assets/quran/qcf4/pages/312.json") as Qcf4PageJson;
    case 313:
      return require("../../assets/quran/qcf4/pages/313.json") as Qcf4PageJson;
    case 314:
      return require("../../assets/quran/qcf4/pages/314.json") as Qcf4PageJson;
    case 315:
      return require("../../assets/quran/qcf4/pages/315.json") as Qcf4PageJson;
    case 316:
      return require("../../assets/quran/qcf4/pages/316.json") as Qcf4PageJson;
    case 317:
      return require("../../assets/quran/qcf4/pages/317.json") as Qcf4PageJson;
    case 318:
      return require("../../assets/quran/qcf4/pages/318.json") as Qcf4PageJson;
    case 319:
      return require("../../assets/quran/qcf4/pages/319.json") as Qcf4PageJson;
    case 320:
      return require("../../assets/quran/qcf4/pages/320.json") as Qcf4PageJson;
    case 321:
      return require("../../assets/quran/qcf4/pages/321.json") as Qcf4PageJson;
    case 322:
      return require("../../assets/quran/qcf4/pages/322.json") as Qcf4PageJson;
    case 323:
      return require("../../assets/quran/qcf4/pages/323.json") as Qcf4PageJson;
    case 324:
      return require("../../assets/quran/qcf4/pages/324.json") as Qcf4PageJson;
    case 325:
      return require("../../assets/quran/qcf4/pages/325.json") as Qcf4PageJson;
    case 326:
      return require("../../assets/quran/qcf4/pages/326.json") as Qcf4PageJson;
    case 327:
      return require("../../assets/quran/qcf4/pages/327.json") as Qcf4PageJson;
    case 328:
      return require("../../assets/quran/qcf4/pages/328.json") as Qcf4PageJson;
    case 329:
      return require("../../assets/quran/qcf4/pages/329.json") as Qcf4PageJson;
    case 330:
      return require("../../assets/quran/qcf4/pages/330.json") as Qcf4PageJson;
    case 331:
      return require("../../assets/quran/qcf4/pages/331.json") as Qcf4PageJson;
    case 332:
      return require("../../assets/quran/qcf4/pages/332.json") as Qcf4PageJson;
    case 333:
      return require("../../assets/quran/qcf4/pages/333.json") as Qcf4PageJson;
    case 334:
      return require("../../assets/quran/qcf4/pages/334.json") as Qcf4PageJson;
    case 335:
      return require("../../assets/quran/qcf4/pages/335.json") as Qcf4PageJson;
    case 336:
      return require("../../assets/quran/qcf4/pages/336.json") as Qcf4PageJson;
    case 337:
      return require("../../assets/quran/qcf4/pages/337.json") as Qcf4PageJson;
    case 338:
      return require("../../assets/quran/qcf4/pages/338.json") as Qcf4PageJson;
    case 339:
      return require("../../assets/quran/qcf4/pages/339.json") as Qcf4PageJson;
    case 340:
      return require("../../assets/quran/qcf4/pages/340.json") as Qcf4PageJson;
    case 341:
      return require("../../assets/quran/qcf4/pages/341.json") as Qcf4PageJson;
    case 342:
      return require("../../assets/quran/qcf4/pages/342.json") as Qcf4PageJson;
    case 343:
      return require("../../assets/quran/qcf4/pages/343.json") as Qcf4PageJson;
    case 344:
      return require("../../assets/quran/qcf4/pages/344.json") as Qcf4PageJson;
    case 345:
      return require("../../assets/quran/qcf4/pages/345.json") as Qcf4PageJson;
    case 346:
      return require("../../assets/quran/qcf4/pages/346.json") as Qcf4PageJson;
    case 347:
      return require("../../assets/quran/qcf4/pages/347.json") as Qcf4PageJson;
    case 348:
      return require("../../assets/quran/qcf4/pages/348.json") as Qcf4PageJson;
    case 349:
      return require("../../assets/quran/qcf4/pages/349.json") as Qcf4PageJson;
    case 350:
      return require("../../assets/quran/qcf4/pages/350.json") as Qcf4PageJson;
    case 351:
      return require("../../assets/quran/qcf4/pages/351.json") as Qcf4PageJson;
    case 352:
      return require("../../assets/quran/qcf4/pages/352.json") as Qcf4PageJson;
    case 353:
      return require("../../assets/quran/qcf4/pages/353.json") as Qcf4PageJson;
    case 354:
      return require("../../assets/quran/qcf4/pages/354.json") as Qcf4PageJson;
    case 355:
      return require("../../assets/quran/qcf4/pages/355.json") as Qcf4PageJson;
    case 356:
      return require("../../assets/quran/qcf4/pages/356.json") as Qcf4PageJson;
    case 357:
      return require("../../assets/quran/qcf4/pages/357.json") as Qcf4PageJson;
    case 358:
      return require("../../assets/quran/qcf4/pages/358.json") as Qcf4PageJson;
    case 359:
      return require("../../assets/quran/qcf4/pages/359.json") as Qcf4PageJson;
    case 360:
      return require("../../assets/quran/qcf4/pages/360.json") as Qcf4PageJson;
    case 361:
      return require("../../assets/quran/qcf4/pages/361.json") as Qcf4PageJson;
    case 362:
      return require("../../assets/quran/qcf4/pages/362.json") as Qcf4PageJson;
    case 363:
      return require("../../assets/quran/qcf4/pages/363.json") as Qcf4PageJson;
    case 364:
      return require("../../assets/quran/qcf4/pages/364.json") as Qcf4PageJson;
    case 365:
      return require("../../assets/quran/qcf4/pages/365.json") as Qcf4PageJson;
    case 366:
      return require("../../assets/quran/qcf4/pages/366.json") as Qcf4PageJson;
    case 367:
      return require("../../assets/quran/qcf4/pages/367.json") as Qcf4PageJson;
    case 368:
      return require("../../assets/quran/qcf4/pages/368.json") as Qcf4PageJson;
    case 369:
      return require("../../assets/quran/qcf4/pages/369.json") as Qcf4PageJson;
    case 370:
      return require("../../assets/quran/qcf4/pages/370.json") as Qcf4PageJson;
    case 371:
      return require("../../assets/quran/qcf4/pages/371.json") as Qcf4PageJson;
    case 372:
      return require("../../assets/quran/qcf4/pages/372.json") as Qcf4PageJson;
    case 373:
      return require("../../assets/quran/qcf4/pages/373.json") as Qcf4PageJson;
    case 374:
      return require("../../assets/quran/qcf4/pages/374.json") as Qcf4PageJson;
    case 375:
      return require("../../assets/quran/qcf4/pages/375.json") as Qcf4PageJson;
    case 376:
      return require("../../assets/quran/qcf4/pages/376.json") as Qcf4PageJson;
    case 377:
      return require("../../assets/quran/qcf4/pages/377.json") as Qcf4PageJson;
    case 378:
      return require("../../assets/quran/qcf4/pages/378.json") as Qcf4PageJson;
    case 379:
      return require("../../assets/quran/qcf4/pages/379.json") as Qcf4PageJson;
    case 380:
      return require("../../assets/quran/qcf4/pages/380.json") as Qcf4PageJson;
    case 381:
      return require("../../assets/quran/qcf4/pages/381.json") as Qcf4PageJson;
    case 382:
      return require("../../assets/quran/qcf4/pages/382.json") as Qcf4PageJson;
    case 383:
      return require("../../assets/quran/qcf4/pages/383.json") as Qcf4PageJson;
    case 384:
      return require("../../assets/quran/qcf4/pages/384.json") as Qcf4PageJson;
    case 385:
      return require("../../assets/quran/qcf4/pages/385.json") as Qcf4PageJson;
    case 386:
      return require("../../assets/quran/qcf4/pages/386.json") as Qcf4PageJson;
    case 387:
      return require("../../assets/quran/qcf4/pages/387.json") as Qcf4PageJson;
    case 388:
      return require("../../assets/quran/qcf4/pages/388.json") as Qcf4PageJson;
    case 389:
      return require("../../assets/quran/qcf4/pages/389.json") as Qcf4PageJson;
    case 390:
      return require("../../assets/quran/qcf4/pages/390.json") as Qcf4PageJson;
    case 391:
      return require("../../assets/quran/qcf4/pages/391.json") as Qcf4PageJson;
    case 392:
      return require("../../assets/quran/qcf4/pages/392.json") as Qcf4PageJson;
    case 393:
      return require("../../assets/quran/qcf4/pages/393.json") as Qcf4PageJson;
    case 394:
      return require("../../assets/quran/qcf4/pages/394.json") as Qcf4PageJson;
    case 395:
      return require("../../assets/quran/qcf4/pages/395.json") as Qcf4PageJson;
    case 396:
      return require("../../assets/quran/qcf4/pages/396.json") as Qcf4PageJson;
    case 397:
      return require("../../assets/quran/qcf4/pages/397.json") as Qcf4PageJson;
    case 398:
      return require("../../assets/quran/qcf4/pages/398.json") as Qcf4PageJson;
    case 399:
      return require("../../assets/quran/qcf4/pages/399.json") as Qcf4PageJson;
    case 400:
      return require("../../assets/quran/qcf4/pages/400.json") as Qcf4PageJson;
    case 401:
      return require("../../assets/quran/qcf4/pages/401.json") as Qcf4PageJson;
    case 402:
      return require("../../assets/quran/qcf4/pages/402.json") as Qcf4PageJson;
    case 403:
      return require("../../assets/quran/qcf4/pages/403.json") as Qcf4PageJson;
    case 404:
      return require("../../assets/quran/qcf4/pages/404.json") as Qcf4PageJson;
    case 405:
      return require("../../assets/quran/qcf4/pages/405.json") as Qcf4PageJson;
    case 406:
      return require("../../assets/quran/qcf4/pages/406.json") as Qcf4PageJson;
    case 407:
      return require("../../assets/quran/qcf4/pages/407.json") as Qcf4PageJson;
    case 408:
      return require("../../assets/quran/qcf4/pages/408.json") as Qcf4PageJson;
    case 409:
      return require("../../assets/quran/qcf4/pages/409.json") as Qcf4PageJson;
    case 410:
      return require("../../assets/quran/qcf4/pages/410.json") as Qcf4PageJson;
    case 411:
      return require("../../assets/quran/qcf4/pages/411.json") as Qcf4PageJson;
    case 412:
      return require("../../assets/quran/qcf4/pages/412.json") as Qcf4PageJson;
    case 413:
      return require("../../assets/quran/qcf4/pages/413.json") as Qcf4PageJson;
    case 414:
      return require("../../assets/quran/qcf4/pages/414.json") as Qcf4PageJson;
    case 415:
      return require("../../assets/quran/qcf4/pages/415.json") as Qcf4PageJson;
    case 416:
      return require("../../assets/quran/qcf4/pages/416.json") as Qcf4PageJson;
    case 417:
      return require("../../assets/quran/qcf4/pages/417.json") as Qcf4PageJson;
    case 418:
      return require("../../assets/quran/qcf4/pages/418.json") as Qcf4PageJson;
    case 419:
      return require("../../assets/quran/qcf4/pages/419.json") as Qcf4PageJson;
    case 420:
      return require("../../assets/quran/qcf4/pages/420.json") as Qcf4PageJson;
    case 421:
      return require("../../assets/quran/qcf4/pages/421.json") as Qcf4PageJson;
    case 422:
      return require("../../assets/quran/qcf4/pages/422.json") as Qcf4PageJson;
    case 423:
      return require("../../assets/quran/qcf4/pages/423.json") as Qcf4PageJson;
    case 424:
      return require("../../assets/quran/qcf4/pages/424.json") as Qcf4PageJson;
    case 425:
      return require("../../assets/quran/qcf4/pages/425.json") as Qcf4PageJson;
    case 426:
      return require("../../assets/quran/qcf4/pages/426.json") as Qcf4PageJson;
    case 427:
      return require("../../assets/quran/qcf4/pages/427.json") as Qcf4PageJson;
    case 428:
      return require("../../assets/quran/qcf4/pages/428.json") as Qcf4PageJson;
    case 429:
      return require("../../assets/quran/qcf4/pages/429.json") as Qcf4PageJson;
    case 430:
      return require("../../assets/quran/qcf4/pages/430.json") as Qcf4PageJson;
    case 431:
      return require("../../assets/quran/qcf4/pages/431.json") as Qcf4PageJson;
    case 432:
      return require("../../assets/quran/qcf4/pages/432.json") as Qcf4PageJson;
    case 433:
      return require("../../assets/quran/qcf4/pages/433.json") as Qcf4PageJson;
    case 434:
      return require("../../assets/quran/qcf4/pages/434.json") as Qcf4PageJson;
    case 435:
      return require("../../assets/quran/qcf4/pages/435.json") as Qcf4PageJson;
    case 436:
      return require("../../assets/quran/qcf4/pages/436.json") as Qcf4PageJson;
    case 437:
      return require("../../assets/quran/qcf4/pages/437.json") as Qcf4PageJson;
    case 438:
      return require("../../assets/quran/qcf4/pages/438.json") as Qcf4PageJson;
    case 439:
      return require("../../assets/quran/qcf4/pages/439.json") as Qcf4PageJson;
    case 440:
      return require("../../assets/quran/qcf4/pages/440.json") as Qcf4PageJson;
    case 441:
      return require("../../assets/quran/qcf4/pages/441.json") as Qcf4PageJson;
    case 442:
      return require("../../assets/quran/qcf4/pages/442.json") as Qcf4PageJson;
    case 443:
      return require("../../assets/quran/qcf4/pages/443.json") as Qcf4PageJson;
    case 444:
      return require("../../assets/quran/qcf4/pages/444.json") as Qcf4PageJson;
    case 445:
      return require("../../assets/quran/qcf4/pages/445.json") as Qcf4PageJson;
    case 446:
      return require("../../assets/quran/qcf4/pages/446.json") as Qcf4PageJson;
    case 447:
      return require("../../assets/quran/qcf4/pages/447.json") as Qcf4PageJson;
    case 448:
      return require("../../assets/quran/qcf4/pages/448.json") as Qcf4PageJson;
    case 449:
      return require("../../assets/quran/qcf4/pages/449.json") as Qcf4PageJson;
    case 450:
      return require("../../assets/quran/qcf4/pages/450.json") as Qcf4PageJson;
    case 451:
      return require("../../assets/quran/qcf4/pages/451.json") as Qcf4PageJson;
    case 452:
      return require("../../assets/quran/qcf4/pages/452.json") as Qcf4PageJson;
    case 453:
      return require("../../assets/quran/qcf4/pages/453.json") as Qcf4PageJson;
    case 454:
      return require("../../assets/quran/qcf4/pages/454.json") as Qcf4PageJson;
    case 455:
      return require("../../assets/quran/qcf4/pages/455.json") as Qcf4PageJson;
    case 456:
      return require("../../assets/quran/qcf4/pages/456.json") as Qcf4PageJson;
    case 457:
      return require("../../assets/quran/qcf4/pages/457.json") as Qcf4PageJson;
    case 458:
      return require("../../assets/quran/qcf4/pages/458.json") as Qcf4PageJson;
    case 459:
      return require("../../assets/quran/qcf4/pages/459.json") as Qcf4PageJson;
    case 460:
      return require("../../assets/quran/qcf4/pages/460.json") as Qcf4PageJson;
    case 461:
      return require("../../assets/quran/qcf4/pages/461.json") as Qcf4PageJson;
    case 462:
      return require("../../assets/quran/qcf4/pages/462.json") as Qcf4PageJson;
    case 463:
      return require("../../assets/quran/qcf4/pages/463.json") as Qcf4PageJson;
    case 464:
      return require("../../assets/quran/qcf4/pages/464.json") as Qcf4PageJson;
    case 465:
      return require("../../assets/quran/qcf4/pages/465.json") as Qcf4PageJson;
    case 466:
      return require("../../assets/quran/qcf4/pages/466.json") as Qcf4PageJson;
    case 467:
      return require("../../assets/quran/qcf4/pages/467.json") as Qcf4PageJson;
    case 468:
      return require("../../assets/quran/qcf4/pages/468.json") as Qcf4PageJson;
    case 469:
      return require("../../assets/quran/qcf4/pages/469.json") as Qcf4PageJson;
    case 470:
      return require("../../assets/quran/qcf4/pages/470.json") as Qcf4PageJson;
    case 471:
      return require("../../assets/quran/qcf4/pages/471.json") as Qcf4PageJson;
    case 472:
      return require("../../assets/quran/qcf4/pages/472.json") as Qcf4PageJson;
    case 473:
      return require("../../assets/quran/qcf4/pages/473.json") as Qcf4PageJson;
    case 474:
      return require("../../assets/quran/qcf4/pages/474.json") as Qcf4PageJson;
    case 475:
      return require("../../assets/quran/qcf4/pages/475.json") as Qcf4PageJson;
    case 476:
      return require("../../assets/quran/qcf4/pages/476.json") as Qcf4PageJson;
    case 477:
      return require("../../assets/quran/qcf4/pages/477.json") as Qcf4PageJson;
    case 478:
      return require("../../assets/quran/qcf4/pages/478.json") as Qcf4PageJson;
    case 479:
      return require("../../assets/quran/qcf4/pages/479.json") as Qcf4PageJson;
    case 480:
      return require("../../assets/quran/qcf4/pages/480.json") as Qcf4PageJson;
    case 481:
      return require("../../assets/quran/qcf4/pages/481.json") as Qcf4PageJson;
    case 482:
      return require("../../assets/quran/qcf4/pages/482.json") as Qcf4PageJson;
    case 483:
      return require("../../assets/quran/qcf4/pages/483.json") as Qcf4PageJson;
    case 484:
      return require("../../assets/quran/qcf4/pages/484.json") as Qcf4PageJson;
    case 485:
      return require("../../assets/quran/qcf4/pages/485.json") as Qcf4PageJson;
    case 486:
      return require("../../assets/quran/qcf4/pages/486.json") as Qcf4PageJson;
    case 487:
      return require("../../assets/quran/qcf4/pages/487.json") as Qcf4PageJson;
    case 488:
      return require("../../assets/quran/qcf4/pages/488.json") as Qcf4PageJson;
    case 489:
      return require("../../assets/quran/qcf4/pages/489.json") as Qcf4PageJson;
    case 490:
      return require("../../assets/quran/qcf4/pages/490.json") as Qcf4PageJson;
    case 491:
      return require("../../assets/quran/qcf4/pages/491.json") as Qcf4PageJson;
    case 492:
      return require("../../assets/quran/qcf4/pages/492.json") as Qcf4PageJson;
    case 493:
      return require("../../assets/quran/qcf4/pages/493.json") as Qcf4PageJson;
    case 494:
      return require("../../assets/quran/qcf4/pages/494.json") as Qcf4PageJson;
    case 495:
      return require("../../assets/quran/qcf4/pages/495.json") as Qcf4PageJson;
    case 496:
      return require("../../assets/quran/qcf4/pages/496.json") as Qcf4PageJson;
    case 497:
      return require("../../assets/quran/qcf4/pages/497.json") as Qcf4PageJson;
    case 498:
      return require("../../assets/quran/qcf4/pages/498.json") as Qcf4PageJson;
    case 499:
      return require("../../assets/quran/qcf4/pages/499.json") as Qcf4PageJson;
    case 500:
      return require("../../assets/quran/qcf4/pages/500.json") as Qcf4PageJson;
    case 501:
      return require("../../assets/quran/qcf4/pages/501.json") as Qcf4PageJson;
    case 502:
      return require("../../assets/quran/qcf4/pages/502.json") as Qcf4PageJson;
    case 503:
      return require("../../assets/quran/qcf4/pages/503.json") as Qcf4PageJson;
    case 504:
      return require("../../assets/quran/qcf4/pages/504.json") as Qcf4PageJson;
    case 505:
      return require("../../assets/quran/qcf4/pages/505.json") as Qcf4PageJson;
    case 506:
      return require("../../assets/quran/qcf4/pages/506.json") as Qcf4PageJson;
    case 507:
      return require("../../assets/quran/qcf4/pages/507.json") as Qcf4PageJson;
    case 508:
      return require("../../assets/quran/qcf4/pages/508.json") as Qcf4PageJson;
    case 509:
      return require("../../assets/quran/qcf4/pages/509.json") as Qcf4PageJson;
    case 510:
      return require("../../assets/quran/qcf4/pages/510.json") as Qcf4PageJson;
    case 511:
      return require("../../assets/quran/qcf4/pages/511.json") as Qcf4PageJson;
    case 512:
      return require("../../assets/quran/qcf4/pages/512.json") as Qcf4PageJson;
    case 513:
      return require("../../assets/quran/qcf4/pages/513.json") as Qcf4PageJson;
    case 514:
      return require("../../assets/quran/qcf4/pages/514.json") as Qcf4PageJson;
    case 515:
      return require("../../assets/quran/qcf4/pages/515.json") as Qcf4PageJson;
    case 516:
      return require("../../assets/quran/qcf4/pages/516.json") as Qcf4PageJson;
    case 517:
      return require("../../assets/quran/qcf4/pages/517.json") as Qcf4PageJson;
    case 518:
      return require("../../assets/quran/qcf4/pages/518.json") as Qcf4PageJson;
    case 519:
      return require("../../assets/quran/qcf4/pages/519.json") as Qcf4PageJson;
    case 520:
      return require("../../assets/quran/qcf4/pages/520.json") as Qcf4PageJson;
    case 521:
      return require("../../assets/quran/qcf4/pages/521.json") as Qcf4PageJson;
    case 522:
      return require("../../assets/quran/qcf4/pages/522.json") as Qcf4PageJson;
    case 523:
      return require("../../assets/quran/qcf4/pages/523.json") as Qcf4PageJson;
    case 524:
      return require("../../assets/quran/qcf4/pages/524.json") as Qcf4PageJson;
    case 525:
      return require("../../assets/quran/qcf4/pages/525.json") as Qcf4PageJson;
    case 526:
      return require("../../assets/quran/qcf4/pages/526.json") as Qcf4PageJson;
    case 527:
      return require("../../assets/quran/qcf4/pages/527.json") as Qcf4PageJson;
    case 528:
      return require("../../assets/quran/qcf4/pages/528.json") as Qcf4PageJson;
    case 529:
      return require("../../assets/quran/qcf4/pages/529.json") as Qcf4PageJson;
    case 530:
      return require("../../assets/quran/qcf4/pages/530.json") as Qcf4PageJson;
    case 531:
      return require("../../assets/quran/qcf4/pages/531.json") as Qcf4PageJson;
    case 532:
      return require("../../assets/quran/qcf4/pages/532.json") as Qcf4PageJson;
    case 533:
      return require("../../assets/quran/qcf4/pages/533.json") as Qcf4PageJson;
    case 534:
      return require("../../assets/quran/qcf4/pages/534.json") as Qcf4PageJson;
    case 535:
      return require("../../assets/quran/qcf4/pages/535.json") as Qcf4PageJson;
    case 536:
      return require("../../assets/quran/qcf4/pages/536.json") as Qcf4PageJson;
    case 537:
      return require("../../assets/quran/qcf4/pages/537.json") as Qcf4PageJson;
    case 538:
      return require("../../assets/quran/qcf4/pages/538.json") as Qcf4PageJson;
    case 539:
      return require("../../assets/quran/qcf4/pages/539.json") as Qcf4PageJson;
    case 540:
      return require("../../assets/quran/qcf4/pages/540.json") as Qcf4PageJson;
    case 541:
      return require("../../assets/quran/qcf4/pages/541.json") as Qcf4PageJson;
    case 542:
      return require("../../assets/quran/qcf4/pages/542.json") as Qcf4PageJson;
    case 543:
      return require("../../assets/quran/qcf4/pages/543.json") as Qcf4PageJson;
    case 544:
      return require("../../assets/quran/qcf4/pages/544.json") as Qcf4PageJson;
    case 545:
      return require("../../assets/quran/qcf4/pages/545.json") as Qcf4PageJson;
    case 546:
      return require("../../assets/quran/qcf4/pages/546.json") as Qcf4PageJson;
    case 547:
      return require("../../assets/quran/qcf4/pages/547.json") as Qcf4PageJson;
    case 548:
      return require("../../assets/quran/qcf4/pages/548.json") as Qcf4PageJson;
    case 549:
      return require("../../assets/quran/qcf4/pages/549.json") as Qcf4PageJson;
    case 550:
      return require("../../assets/quran/qcf4/pages/550.json") as Qcf4PageJson;
    case 551:
      return require("../../assets/quran/qcf4/pages/551.json") as Qcf4PageJson;
    case 552:
      return require("../../assets/quran/qcf4/pages/552.json") as Qcf4PageJson;
    case 553:
      return require("../../assets/quran/qcf4/pages/553.json") as Qcf4PageJson;
    case 554:
      return require("../../assets/quran/qcf4/pages/554.json") as Qcf4PageJson;
    case 555:
      return require("../../assets/quran/qcf4/pages/555.json") as Qcf4PageJson;
    case 556:
      return require("../../assets/quran/qcf4/pages/556.json") as Qcf4PageJson;
    case 557:
      return require("../../assets/quran/qcf4/pages/557.json") as Qcf4PageJson;
    case 558:
      return require("../../assets/quran/qcf4/pages/558.json") as Qcf4PageJson;
    case 559:
      return require("../../assets/quran/qcf4/pages/559.json") as Qcf4PageJson;
    case 560:
      return require("../../assets/quran/qcf4/pages/560.json") as Qcf4PageJson;
    case 561:
      return require("../../assets/quran/qcf4/pages/561.json") as Qcf4PageJson;
    case 562:
      return require("../../assets/quran/qcf4/pages/562.json") as Qcf4PageJson;
    case 563:
      return require("../../assets/quran/qcf4/pages/563.json") as Qcf4PageJson;
    case 564:
      return require("../../assets/quran/qcf4/pages/564.json") as Qcf4PageJson;
    case 565:
      return require("../../assets/quran/qcf4/pages/565.json") as Qcf4PageJson;
    case 566:
      return require("../../assets/quran/qcf4/pages/566.json") as Qcf4PageJson;
    case 567:
      return require("../../assets/quran/qcf4/pages/567.json") as Qcf4PageJson;
    case 568:
      return require("../../assets/quran/qcf4/pages/568.json") as Qcf4PageJson;
    case 569:
      return require("../../assets/quran/qcf4/pages/569.json") as Qcf4PageJson;
    case 570:
      return require("../../assets/quran/qcf4/pages/570.json") as Qcf4PageJson;
    case 571:
      return require("../../assets/quran/qcf4/pages/571.json") as Qcf4PageJson;
    case 572:
      return require("../../assets/quran/qcf4/pages/572.json") as Qcf4PageJson;
    case 573:
      return require("../../assets/quran/qcf4/pages/573.json") as Qcf4PageJson;
    case 574:
      return require("../../assets/quran/qcf4/pages/574.json") as Qcf4PageJson;
    case 575:
      return require("../../assets/quran/qcf4/pages/575.json") as Qcf4PageJson;
    case 576:
      return require("../../assets/quran/qcf4/pages/576.json") as Qcf4PageJson;
    case 577:
      return require("../../assets/quran/qcf4/pages/577.json") as Qcf4PageJson;
    case 578:
      return require("../../assets/quran/qcf4/pages/578.json") as Qcf4PageJson;
    case 579:
      return require("../../assets/quran/qcf4/pages/579.json") as Qcf4PageJson;
    case 580:
      return require("../../assets/quran/qcf4/pages/580.json") as Qcf4PageJson;
    case 581:
      return require("../../assets/quran/qcf4/pages/581.json") as Qcf4PageJson;
    case 582:
      return require("../../assets/quran/qcf4/pages/582.json") as Qcf4PageJson;
    case 583:
      return require("../../assets/quran/qcf4/pages/583.json") as Qcf4PageJson;
    case 584:
      return require("../../assets/quran/qcf4/pages/584.json") as Qcf4PageJson;
    case 585:
      return require("../../assets/quran/qcf4/pages/585.json") as Qcf4PageJson;
    case 586:
      return require("../../assets/quran/qcf4/pages/586.json") as Qcf4PageJson;
    case 587:
      return require("../../assets/quran/qcf4/pages/587.json") as Qcf4PageJson;
    case 588:
      return require("../../assets/quran/qcf4/pages/588.json") as Qcf4PageJson;
    case 589:
      return require("../../assets/quran/qcf4/pages/589.json") as Qcf4PageJson;
    case 590:
      return require("../../assets/quran/qcf4/pages/590.json") as Qcf4PageJson;
    case 591:
      return require("../../assets/quran/qcf4/pages/591.json") as Qcf4PageJson;
    case 592:
      return require("../../assets/quran/qcf4/pages/592.json") as Qcf4PageJson;
    case 593:
      return require("../../assets/quran/qcf4/pages/593.json") as Qcf4PageJson;
    case 594:
      return require("../../assets/quran/qcf4/pages/594.json") as Qcf4PageJson;
    case 595:
      return require("../../assets/quran/qcf4/pages/595.json") as Qcf4PageJson;
    case 596:
      return require("../../assets/quran/qcf4/pages/596.json") as Qcf4PageJson;
    case 597:
      return require("../../assets/quran/qcf4/pages/597.json") as Qcf4PageJson;
    case 598:
      return require("../../assets/quran/qcf4/pages/598.json") as Qcf4PageJson;
    case 599:
      return require("../../assets/quran/qcf4/pages/599.json") as Qcf4PageJson;
    case 600:
      return require("../../assets/quran/qcf4/pages/600.json") as Qcf4PageJson;
    case 601:
      return require("../../assets/quran/qcf4/pages/601.json") as Qcf4PageJson;
    case 602:
      return require("../../assets/quran/qcf4/pages/602.json") as Qcf4PageJson;
    case 603:
      return require("../../assets/quran/qcf4/pages/603.json") as Qcf4PageJson;
    case 604:
      return require("../../assets/quran/qcf4/pages/604.json") as Qcf4PageJson;
    default:
      return null;
  }
}
