import { Platform, StyleSheet } from "react-native";
import type { ThemeColors } from "../theme/colors";
import type { MushafTypographyMetrics } from "../quran/mushafTypography";
import {
  resolveQuranReadingTheme,
  type QuranReadingThemeId,
} from "../theme/quranComReadingTheme";
import { QURAN_BOOK_FONT_FACE } from "../fonts/quranBookFonts";
import { QURAN_SCREEN_HORIZONTAL_PADDING } from "../quran/quranResponsiveLayout";
import { quranArabicNoClipTextStyle } from "../quran/quranArabicNoClipTextStyle";
import { quranSurahListTypography } from "../theme/quranSurahListTheme";

export type QuranSurahScreenStyles = ReturnType<typeof makeQuranSurahScreenStyles>;

export function makeQuranSurahScreenStyles(
  colors: ThemeColors,
  isDark: boolean,
  mushMetrics: MushafTypographyMetrics,
  mushafLayout: boolean,
  readingThemeId: QuranReadingThemeId
) {
  const readingTheme = resolveQuranReadingTheme(readingThemeId);
  const bookDesk = readingTheme.desk;
  const uiBg = readingTheme.pageFace;
  const uiCard = readingTheme.pageFace;
  const uiBorder = readingTheme.pageBorderColor;
  const uiText = readingTheme.titleInk;
  const uiMuted = readingTheme.chromeInk;
  const quranChromeBorder = readingTheme.pageBorderColor;
  const quranChromeSurface = readingTheme.titlePaperBg;
  /** Аят арабы: muftyat оқулық нақышында жасыл, басқа пресеттерде қара/ақ. */
  const {
    scale,
    arabAyahFont,
    mushafArabSize,
    mushafArabLineHeight,
    mushafTitleFs,
    mushafTitleLh,
    mushafBismFont,
    mushafBismLh,
    densityLayout,
  } = mushMetrics;
  const quranAyahArabicInk = readingTheme.arabicInk;
  const mushafMutedInk = uiMuted;
  const mushafStrongInk = uiText;
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: uiBg, position: "relative" },
    mushafBookFlatList: { flex: 1 },
    mushafPagerHost: {
      direction: "ltr",
      flex: 1,
      minHeight: 0,
      backgroundColor: bookDesk,
    },
    mushafPagerPageShell: {
      flex: 1,
      minHeight: 0,
      overflow: "hidden",
    },
    center: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: uiBg,
      padding: 24,
    },
    muted: { color: uiMuted, marginTop: 12 },
    err: { color: colors.error, textAlign: "center", lineHeight: 20 },
    errorActions: {
      marginTop: 18,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
    },
    errorPrimaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: colors.accent,
    },
    errorPrimaryBtnText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
    errorSecondaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: uiBorder,
      backgroundColor: uiCard,
    },
    errorSecondaryBtnText: { color: colors.text, fontSize: 13, fontWeight: "800" },
    topBar: {
      paddingLeft: 8,
      paddingBottom: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    /** Ayah: сол жақта сүре латын, оңда джуз. */
    topBarMid: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 4,
      gap: 8,
    },
    topBarSurahLatin: {
      flex: 1,
      minWidth: 0,
      color: uiText,
      fontSize: 15,
      fontWeight: "800",
      letterSpacing: 0.15,
    },
    topBarJuzPart: {
      color: uiText,
      fontSize: 13,
      fontWeight: "800",
      flexShrink: 1,
      minWidth: 0,
    },
    topBarJuzCluster: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      flexShrink: 1,
      minWidth: 0,
      maxWidth: "52%",
    },
    topBarJuzPickerBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 0,
      borderColor: quranChromeBorder,
      backgroundColor: quranChromeSurface,
      alignItems: "center",
      justifyContent: "center",
    },
    topBarJuzPickerBtnMushaf: {
      borderColor: isDark ? "rgba(255,255,255,0.22)" : quranChromeBorder,
      backgroundColor: "transparent",
    },
    topBarRight: { flexDirection: "row", alignItems: "center", gap: 4 },
    ayahMenuImlaBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 8,
      paddingVertical: 8,
      marginTop: 4,
      marginBottom: 8,
      borderRadius: 10,
      borderWidth: 0,
      borderColor: uiBorder,
      backgroundColor: isDark ? "rgba(255,255,255,0.06)" : quranChromeSurface,
    },
    ayahMenuImlaHint: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      fontWeight: "800",
      color: uiMuted,
    },
    ayahMenuImlaPill: {
      flexShrink: 0,
      maxWidth: 160,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: isDark ? "rgba(38,166,154,0.22)" : "rgba(38,166,154,0.14)",
      borderWidth: 1,
      borderColor: colors.accent,
    },
    ayahMenuImlaPillTurkish: {
      borderColor: colors.prayerCalmGreen,
      backgroundColor: isDark ? "rgba(77,182,172,0.22)" : "rgba(77,182,172,0.18)",
    },
    ayahMenuImlaPillTxt: {
      fontSize: 12,
      fontWeight: "900",
      color: uiText,
    },
    topBarBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      borderWidth: 0,
      borderColor: quranChromeBorder,
      backgroundColor: quranChromeSurface,
      alignItems: "center",
      justifyContent: "center",
    },
    topBarStar: {
      color: colors.accent,
      fontSize: 20,
      fontWeight: "800",
      lineHeight: 20,
    },
    mushafTopBar: {
      backgroundColor: uiBg,
      borderBottomWidth: 0,
      borderBottomColor: "transparent",
    },
    mushafTopBarMid: {
      backgroundColor: "transparent",
    },
    mushafAyahAudioLoadingBar: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "stretch",
      justifyContent: "center",
      gap: 10,
      paddingVertical: 8,
      paddingHorizontal: 14,
      marginHorizontal: 12,
      marginBottom: 4,
      borderRadius: 10,
      borderWidth: 0,
      borderColor: uiBorder,
      backgroundColor: isDark ? "rgba(255,255,255,0.06)" : quranChromeSurface,
    },
    mushafAyahAudioLoadingTxt: {
      fontSize: 13,
      fontWeight: "600",
      color: uiText,
      flexShrink: 1,
    },
    mushafTopBarBtn: {
      borderColor: isDark ? "rgba(255,255,255,0.14)" : quranChromeBorder,
      backgroundColor: isDark ? "rgba(255,255,255,0.06)" : quranChromeSurface,
    },
    mushafTopSurahLatin: {
      flex: 1,
      minWidth: 0,
      color: uiMuted,
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: 0.2,
    },
    mushafTopHeaderCenter: {
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    mushafTopTitleCenter: {
      ...quranSurahListTypography.readerTitle,
      color: uiText,
      alignSelf: "stretch",
    },
    mushafTopSubtitleCenter: {
      ...quranSurahListTypography.readerSubtitle,
      color: uiMuted,
      alignSelf: "stretch",
    },
    mushafTopHeaderRow: {
      flex: 1,
      minWidth: 0,
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 10,
    },
    mushafTopLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      flexShrink: 0,
    },
    mushafTopJuzLeft: {
      color: uiText,
      fontSize: 13,
      fontWeight: "600",
    },
    mushafTopRight: {
      flex: 1,
      minWidth: 0,
      alignItems: "flex-end",
    },
    mushafTopSurahLatinRight: {
      color: uiText,
      fontSize: 14,
      fontWeight: "600",
      textAlign: "right",
    },
    mushafTopSurahArRight: {
      marginTop: 2,
      color: uiMuted,
      fontSize: 14,
      fontWeight: "400",
      textAlign: "right",
      writingDirection: "rtl",
    },
    mushafTopJuzPart: {
      flexShrink: 1,
      minWidth: 0,
      flex: 1,
      color: uiText,
      fontSize: 13,
      fontWeight: "600",
    },
    mushafSurahTitleBlock: {
      alignSelf: "stretch",
      alignItems: "center",
      paddingBottom: 2,
      marginBottom: 10,
    },
    mushafSurahTitlePaper: {
      alignSelf: "center",
      maxWidth: "96%",
      marginTop: 4,
      paddingVertical: 0,
      paddingHorizontal: 0,
      backgroundColor: "transparent",
      borderBottomWidth: 0,
      borderBottomColor: "transparent",
    },
    mushafSurahTitleAr: {
      color: uiText,
      fontSize: 24,
      fontWeight: "400",
      writingDirection: "rtl",
      textAlign: "center",
      lineHeight: 40,
      letterSpacing: 0.04,
      ...Platform.select({
        web: {
          fontFamily: `"${QURAN_BOOK_FONT_FACE.amiri}", "Scheherazade New", "Noto Naskh Arabic", serif`,
        },
        default: { fontFamily: QURAN_BOOK_FONT_FACE.amiri },
      }),
    },
    mushafBismillahBanner: {
      borderColor: "transparent",
      backgroundColor: "transparent",
      marginBottom: densityLayout.mushafBismillahBannerMarginBottom,
      paddingVertical: densityLayout.mushafBismillahBannerPaddingVertical,
      paddingHorizontal: 10,
    },
    mushafBismillahBannerTxt: {
      textAlign: "center",
      color: quranAyahArabicInk,
      ...(mushafBismFont ? { fontSize: mushafBismFont } : { fontSize: Math.round(36 * scale) }),
      ...(mushafBismLh ? { lineHeight: mushafBismLh } : { lineHeight: Math.round(52 * scale) }),
      letterSpacing: 0,
      ...(arabAyahFont.fontFamily
        ? { fontFamily: arabAyahFont.fontFamily }
        : { fontFamily: QURAN_BOOK_FONT_FACE.lateef }),
    },
    mushafListPad: { paddingHorizontal: QURAN_SCREEN_HORIZONTAL_PADDING, paddingTop: 10 },
    /** Мұсаф скролл: арабтан кейінгі транскрипция/мағына блоктары */
    mushafSecondaryAyahBlock: {
      alignSelf: "stretch",
      marginTop: 12,
      paddingBottom: 2,
    },
    mushafSecondaryAyahRibbon: {
      alignSelf: "stretch",
      textAlign: "right",
      writingDirection: "rtl",
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 0.4,
      color: uiMuted,
      marginBottom: 4,
      ...Platform.select({
        web: arabAyahFont.fontFamily ? { fontFamily: arabAyahFont.fontFamily } : {},
        default: arabAyahFont.fontFamily
          ? { fontFamily: arabAyahFont.fontFamily }
          : { fontFamily: QURAN_BOOK_FONT_FACE.lateef },
      }),
    },
    mushafAyahRow: {
      marginBottom: densityLayout.mushafAyahRowMarginBottom,
      paddingVertical: densityLayout.mushafAyahRowPaddingVertical,
      alignSelf: "stretch",
    },
    mushafAyahRowResumeHighlight: {
      borderLeftWidth: 0,
      borderLeftColor: "transparent",
      paddingLeft: 6,
      marginLeft: -2,
      borderRadius: 2,
    },
    mushafAyahArabicCluster: {
      width: "100%",
      flexDirection: "row",
      flexWrap: "wrap",
      direction: "rtl",
      alignItems: "flex-start",
      alignContent: "flex-start",
      justifyContent: "flex-start",
      gap: densityLayout.mushafAyahArabicClusterGap,
      overflow: "visible",
    },
    mushafAyahBookmarkRail: {
      width: 14,
      paddingTop: 3,
      alignItems: "center",
      justifyContent: "flex-start",
    },
    mushafAyahBookmarkDot: {
      width: 11,
      height: 11,
      borderRadius: 6,
      borderWidth: 0,
      borderColor: "transparent",
    },
    /** Мұсаф аят белгісі. */
    mushafAyahMarkerOuter: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 0,
      borderColor: "transparent",
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 0,
    },
    mushafAyahMarkerInner: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 0,
      borderColor: "transparent",
    },
    mushafAyahMarkerTxt: {
      color: uiMuted,
      fontSize: Math.max(12, Math.round(13 * scale)),
      fontWeight: "400",
      letterSpacing: 0.32,
      ...Platform.select({
        web: arabAyahFont.fontFamily ? { fontFamily: arabAyahFont.fontFamily } : {},
        default: arabAyahFont.fontFamily
          ? { fontFamily: arabAyahFont.fontFamily }
          : { fontFamily: QURAN_BOOK_FONT_FACE.lateef },
      }),
    },
    mushafAyahArabicWrap: {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: "auto",
      minWidth: 0,
      maxWidth: "100%",
      alignSelf: "stretch",
      overflow: "visible",
    },
    mushafAyahArabicTap: {
      position: "relative",
      alignSelf: "stretch",
      maxWidth: "100%",
    },
    mushafAyahArabicTapPressed: {
      backgroundColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(0,0,0,0.05)",
      borderRadius: 12,
    },
    mushafAyahTxt: quranArabicNoClipTextStyle({
      color: quranAyahArabicInk,
      writingDirection: "rtl",
      textAlign: "right",
      flexShrink: 1,
      minWidth: 0,
      maxWidth: "100%",
      alignSelf: "stretch",
      ...arabAyahFont,
      ...(mushafArabSize ? { fontSize: mushafArabSize } : null),
      ...(mushafArabLineHeight ? { lineHeight: mushafArabLineHeight } : null),
      letterSpacing: 0.12,
    }),
    /** Мұсаф кітап көрінісі: қазақша/транскрипция — кітап денесі қарпі мен жылы сия */
    mushafAyahSectionCaption: {
      marginTop: 4,
      marginBottom: 2,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.6,
      color: uiMuted,
      textAlign: "center",
      width: "100%",
    },
    mushafAyahKiril: {
      marginTop: 0,
      color: uiText,
      fontSize: 15,
      lineHeight: 24,
      textAlign: "center",
      fontWeight: "500",
      width: "100%",
      ...Platform.select({
        ios: { fontFamily: "Georgia" },
        android: { fontFamily: "serif" },
        default: {},
      }),
    },
    mushafAyahKk: {
      marginTop: 0,
      color: uiText,
      fontSize: 16,
      lineHeight: 27,
      textAlign: "center",
      fontWeight: "500",
      width: "100%",
      ...Platform.select({
        ios: { fontFamily: "Georgia" },
        android: { fontFamily: "serif" },
        default: {},
      }),
    },
    mushafNoKkHint: {
      marginTop: 8,
      fontSize: 11,
      lineHeight: 17,
      fontStyle: "italic",
      color: uiMuted,
      textAlign: "center",
      width: "100%",
    },
    mushafFooter: {
      alignSelf: "stretch",
      alignItems: "flex-end",
      paddingTop: 10,
      paddingBottom: 4,
      paddingHorizontal: 4,
    },
    mushafFooterPill: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "transparent",
      backgroundColor: "transparent",
      overflow: "hidden",
    },
    mushafFooterSep: {
      width: 0,
      height: 22,
      backgroundColor: "transparent",
    },
    mushafFooterPillHizb: {
      fontSize: 12,
      fontWeight: "700",
      color: uiMuted,
      maxWidth: 200,
      paddingVertical: 8,
      paddingLeft: 12,
      paddingRight: 8,
    },
    mushafFooterPillNumWrap: {
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 6,
      paddingHorizontal: 10,
      minHeight: 40,
      backgroundColor: "transparent",
    },
    mushafFooterPillNum: {
      fontSize: 16,
      fontWeight: "800",
      color: uiText,
      textAlign: "center",
    },
    mushafFooterPillEdition: {
      fontSize: 10,
      fontWeight: "700",
      marginTop: 2,
      color: uiMuted,
      textAlign: "center",
      maxWidth: 88,
    },
    en: { color: uiText, fontWeight: "700", fontSize: 22, textAlign: "center" },
    ar: {
      color: uiMuted,
      fontSize: 15,
      marginTop: 8,
      writingDirection: "rtl",
      textAlign: "center",
    },
    toastWrap: {
      position: "absolute",
      left: 16,
      right: 16,
      zIndex: 50,
      backgroundColor: colors.card,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: colors.accent,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    toastTxt: { color: colors.text, fontSize: 14, fontWeight: "700", textAlign: "center" },
    pad: { paddingHorizontal: 12, paddingBottom: 40 },
    ayahCol: { flex: 1, minWidth: 0 },
    ayahArBlock: {
      width: "100%",
      alignItems: "flex-end",
    },
    ayahRow: {
      alignItems: "stretch",
      marginBottom: 18,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "transparent",
      backgroundColor: uiBg,
      paddingVertical: 0,
      paddingHorizontal: 0,
    },
    /** Ayah: таңдалған / ойнап тұрған аят */
    ayahRowAudioFocus: {
      backgroundColor: "transparent",
      borderColor: "transparent",
    },
    bismillahBanner: {
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 20,
      paddingHorizontal: 14,
      marginBottom: 12,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: "transparent",
      backgroundColor: "transparent",
    },
    bismillahBannerTxt: quranArabicNoClipTextStyle({
      color: quranAyahArabicInk,
      writingDirection: "rtl",
      textAlign: "center",
      ...arabAyahFont,
      fontSize:
        typeof arabAyahFont.fontSize === "number" ? Math.round(arabAyahFont.fontSize * 1.12) : 36,
      lineHeight:
        typeof arabAyahFont.lineHeight === "number" ? Math.round(arabAyahFont.lineHeight * 1.08) : 58,
      fontWeight: "500",
      letterSpacing: 0.5,
    }),
    ayahMainTap: { minWidth: 0 },
    /** Дыбыс тек араб мәтінін басқанда */
    ayahArabicTap: {
      position: "relative",
      alignSelf: "stretch",
      maxWidth: "100%",
    },
    ayahArabicTapPressed: {
      backgroundColor: "transparent",
      borderRadius: 0,
    },
    ayahArabicTapDisabled: { opacity: 0.85 },
    ayahArabicLoadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: isDark ? "rgba(0,0,0,0.35)" : "rgba(255,255,255,0.4)",
    },
    ayahIndexInline: {
      color: uiMuted,
      fontSize: 12,
      marginBottom: 8,
      fontWeight: "700",
      textAlign: "center",
      width: "100%",
    },
    ayahTxt: quranArabicNoClipTextStyle({
      color: quranAyahArabicInk,
      writingDirection: "rtl",
      textAlign: "right",
      ...arabAyahFont,
      ...(mushafArabSize ? { fontSize: mushafArabSize } : null),
      ...(mushafArabLineHeight ? { lineHeight: mushafArabLineHeight } : null),
    }),
    /** Арабтан кейінгі оқылу + мағына: орталықтан (оқу қолданбаларының кең тараған түрі). */
    ayahBelowArabic: {
      width: "100%",
      marginTop: 10,
      alignItems: "center",
    },
    /** Транскрипция / қазақша мағына: секция тақырыбы (мұсаф астындағы блоктар үшін де қолданылады) */
    ayahSectionCaption: {
      marginTop: 12,
      marginBottom: 4,
      fontSize: 11,
      fontWeight: "600",
      color: uiMuted,
      letterSpacing: 0.2,
      textAlign: "center",
      width: "100%",
    },
    ayahKiril: {
      marginTop: 0,
      color: uiText,
      fontSize: 16,
      lineHeight: 26,
      textAlign: "center",
      fontWeight: "700",
      width: "100%",
    },
    noKkHint: {
      marginTop: 10,
      fontSize: 12,
      lineHeight: 18,
      color: uiMuted,
      textAlign: "center",
      width: "100%",
    },
    ayahKk: {
      marginTop: 0,
      color: uiText,
      fontSize: 17,
      lineHeight: 28,
      textAlign: "center",
      fontWeight: "700",
      width: "100%",
    },
    ayahInlineAudioControl: {
      marginTop: 10,
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: "rgba(0,0,0,0.04)",
    },
    ayahInlineAudioText: {
      color: uiMuted,
      fontSize: 12,
      fontWeight: "800",
    },
    mushafInlineAudioControl: {
      marginTop: 8,
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: "rgba(0,0,0,0.04)",
    },
    mushafInlineAudioText: {
      color: uiMuted,
      fontSize: 12,
      fontWeight: "800",
    },
    readerSettingsRoot: { flex: 1, justifyContent: "flex-end" },
    readerSettingsBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.4)",
    },
    readerSettingsSheet: {
      alignSelf: "stretch",
      marginHorizontal: 10,
      marginBottom: 6,
      backgroundColor: uiCard,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: uiBorder,
      paddingHorizontal: 18,
      paddingTop: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: isDark ? 0.35 : 0.12,
      shadowRadius: 12,
      elevation: 16,
    },
    readerSettingsHandle: {
      alignSelf: "center",
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: isDark ? "rgba(255,255,255,0.2)" : "rgba(0,0,0,0.12)",
      marginBottom: 14,
    },
    readerSettingsTitle: {
      color: uiText,
      fontSize: 18,
      fontWeight: "900",
      textAlign: "center",
      marginBottom: 18,
    },
    translationSheetContent: {
      paddingHorizontal: 4,
      paddingBottom: 6,
    },
    translationSectionTitle: {
      marginTop: 12,
      marginBottom: 6,
      color: colors.accent,
      fontSize: 13,
      fontWeight: "900",
      letterSpacing: 0.2,
      textTransform: "uppercase",
    },
    translationArabicText: {
      ...arabAyahFont,
      color: uiText,
      fontSize: Math.max(mushafArabSize ?? 30, 30),
      lineHeight: Math.max(mushafArabLineHeight ?? 54, 54),
      textAlign: "right",
      writingDirection: "rtl",
    },
    translationBodyText: {
      color: uiText,
      fontSize: 17,
      lineHeight: 26,
      fontWeight: "700",
    },
    translationTafsirText: {
      color: uiMuted,
      fontSize: 15,
      lineHeight: 23,
      fontWeight: "600",
    },
    readerSectionSubtitle: {
      color: uiText,
      fontSize: 15,
      fontWeight: "800",
      marginBottom: 6,
    },
    readerAccordionWrap: {
      marginTop: 14,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(0,0,0,0.08)",
    },
    readerAccordionWrapFirst: {
      marginTop: 0,
      paddingTop: 0,
      borderTopWidth: 0,
    },
    readerAccordionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      paddingVertical: 4,
    },
    readerAccordionHeaderTitle: {
      flex: 1,
      color: uiText,
      fontSize: 15,
      fontWeight: "800",
    },
    readerAccordionPanel: {
      marginTop: 6,
    },
    readerSettingsScrollPad: {
      paddingBottom: 8,
    },
    readerSectionDividerWrap: {
      marginTop: 16,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(0,0,0,0.08)",
    },
    readerChoiceRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: uiBorder,
      backgroundColor: uiBg,
    },
    readerChoiceRowSelected: {
      borderColor: colors.accent,
      backgroundColor: isDark ? "rgba(77,182,172,0.14)" : "rgba(21,128,61,0.1)",
    },
    juzPickerRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: uiBorder,
      backgroundColor: uiBg,
    },
    juzPickerRowTextCol: { flex: 1, minWidth: 0 },
    juzPickerRowTitle: { color: uiText, fontSize: 15, fontWeight: "800" },
    juzPickerRowSub: { color: uiMuted, fontSize: 12, marginTop: 3, lineHeight: 16 },
    readerChoiceLabel: {
      flex: 1,
      color: uiText,
      fontSize: 14,
      fontWeight: "700",
    },
    readerMushafScaleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
      marginTop: 10,
      marginBottom: 4,
    },
    readerMushafScaleBtn: {
      width: 44,
      height: 44,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: uiBorder,
      backgroundColor: uiCard,
      alignItems: "center",
      justifyContent: "center",
    },
    readerMushafScaleValue: {
      minWidth: 56,
      textAlign: "center",
      fontSize: 16,
      fontWeight: "900",
      color: uiText,
    },
    readerSettingRowAfterContent: {
      marginTop: 16,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(0,0,0,0.08)",
    },
    readerSettingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      paddingVertical: 4,
    },
    readerSettingRowLabel: {
      flex: 1,
      color: uiText,
      fontSize: 16,
      fontWeight: "800",
    },
    readerSettingsHint: {
      color: uiMuted,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 8,
      marginBottom: 4,
    },
    readerTajweedExplainShort: {
      color: uiMuted,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 4,
      marginBottom: 8,
      fontWeight: "600",
    },
    readerSettingsLoading: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginTop: 12,
      marginBottom: 4,
    },
    readerSettingsLoadingTxt: { color: uiMuted, fontSize: 12, fontWeight: "600", flex: 1 },
    readerLegendBtn: {
      marginTop: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.2)" : quranChromeBorder,
      backgroundColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(255,255,255,0.94)",
    },
    readerLegendBtnTxt: {
      flex: 1,
      color: uiText,
      fontSize: 15,
      fontWeight: "800",
    },
    readerSettingsDoneBtn: {
      marginTop: 14,
      marginBottom: 4,
      paddingVertical: 14,
      borderRadius: 14,
      alignItems: "center",
      backgroundColor: isDark ? "rgba(77,182,172,0.22)" : "rgba(21,128,61,0.14)",
    },
    readerSettingsDoneTxt: { color: colors.accent, fontSize: 16, fontWeight: "900" },
    legendBackdrop: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    legendDismiss: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.45)",
    },
    legendCard: {
      width: "88%",
      maxHeight: "78%",
      zIndex: 2,
      backgroundColor: uiCard,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: uiBorder,
      padding: 16,
    },
    legendTitle: { color: uiText, fontSize: 16, fontWeight: "900", marginBottom: 8 },
    legendIntro: {
      color: uiMuted,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: "600",
      marginBottom: 12,
    },
    legendScroll: { maxHeight: 420 },
    legendLine: { flexDirection: "row", alignItems: "flex-start", gap: 10, marginBottom: 12 },
    legendDot: { width: 12, height: 12, borderRadius: 6, marginTop: 5 },
    legendTxtCol: { flex: 1, minWidth: 0 },
    legendRuleTitle: { color: uiText, fontSize: 14, lineHeight: 20, fontWeight: "800" },
    legendTag: { color: uiMuted, fontSize: 12, fontWeight: "600" },
    legendTxt: { flex: 1, color: uiText, fontSize: 13, lineHeight: 20, fontWeight: "600" },
    legendTxtMultiline: { color: uiMuted, fontSize: 12, lineHeight: 18, fontWeight: "500", marginTop: 2 },
    legendFoot: {
      marginTop: 8,
      color: uiMuted,
      fontSize: 11,
      lineHeight: 16,
      fontStyle: "italic",
    },
    legendCloseBtn: {
      marginTop: 12,
      alignSelf: "stretch",
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: quranChromeSurface,
      borderWidth: 1,
      borderColor: quranChromeBorder,
      alignItems: "center",
    },
    legendCloseTxt: { color: colors.accent, fontSize: 15, fontWeight: "800" },
  });
}
