/** Auto-generated — do not edit. Regen: node scripts/generate-tajweed-letter-asset-map.cjs */
export const TAJWEED_LETTER_ASSET_BY_FILE: Record<string, number> = {
  "alif.mp3": require("../../assets/tajweed/letters/alif.mp3"),
  "ayn.mp3": require("../../assets/tajweed/letters/ayn.mp3"),
  "ba.mp3": require("../../assets/tajweed/letters/ba.mp3"),
  "dad.mp3": require("../../assets/tajweed/letters/dad.mp3"),
  "dal.mp3": require("../../assets/tajweed/letters/dal.mp3"),
  "dhal.mp3": require("../../assets/tajweed/letters/dhal.mp3"),
  "fa.mp3": require("../../assets/tajweed/letters/fa.mp3"),
  "ghayn.mp3": require("../../assets/tajweed/letters/ghayn.mp3"),
  "ha.mp3": require("../../assets/tajweed/letters/ha.mp3"),
  "ha_end.mp3": require("../../assets/tajweed/letters/ha_end.mp3"),
  "jim.mp3": require("../../assets/tajweed/letters/jim.mp3"),
  "kaf.mp3": require("../../assets/tajweed/letters/kaf.mp3"),
  "kha.mp3": require("../../assets/tajweed/letters/kha.mp3"),
  "lam.mp3": require("../../assets/tajweed/letters/lam.mp3"),
  "mim.mp3": require("../../assets/tajweed/letters/mim.mp3"),
  "nun.mp3": require("../../assets/tajweed/letters/nun.mp3"),
  "qaf.mp3": require("../../assets/tajweed/letters/qaf.mp3"),
  "ra.mp3": require("../../assets/tajweed/letters/ra.mp3"),
  "sad.mp3": require("../../assets/tajweed/letters/sad.mp3"),
  "shin.mp3": require("../../assets/tajweed/letters/shin.mp3"),
  "sin.mp3": require("../../assets/tajweed/letters/sin.mp3"),
  "ta.mp3": require("../../assets/tajweed/letters/ta.mp3"),
  "ta_emph.mp3": require("../../assets/tajweed/letters/ta_emph.mp3"),
  "tha.mp3": require("../../assets/tajweed/letters/tha.mp3"),
  "waw.mp3": require("../../assets/tajweed/letters/waw.mp3"),
  "ya.mp3": require("../../assets/tajweed/letters/ya.mp3"),
  "za_emph.mp3": require("../../assets/tajweed/letters/za_emph.mp3"),
  "zay.mp3": require("../../assets/tajweed/letters/zay.mp3"),
};
